[2025-03-20T19:28:24.520-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T19:28:24.527-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: proceso_etl.tarea_formateo manual__2025-03-21T00:28:19.235584+00:00 [queued]>
[2025-03-20T19:28:24.531-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: proceso_etl.tarea_formateo manual__2025-03-21T00:28:19.235584+00:00 [queued]>
[2025-03-20T19:28:24.531-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-20T19:28:24.548-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): tarea_formateo> on 2025-03-21 00:28:19.235584+00:00
[2025-03-20T19:28:24.555-0500] {standard_task_runner.py:72} INFO - Started process 51279 to run task
[2025-03-20T19:28:24.558-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'proceso_etl', 'tarea_formateo', 'manual__2025-03-21T00:28:19.235584+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpbzid64pf']
[2025-03-20T19:28:24.559-0500] {standard_task_runner.py:105} INFO - Job 49: Subtask tarea_formateo
[2025-03-20T19:28:24.587-0500] {task_command.py:467} INFO - Running <TaskInstance: proceso_etl.tarea_formateo manual__2025-03-21T00:28:19.235584+00:00 [running]> on host luis-GF65
[2025-03-20T19:28:24.647-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='proceso_etl' AIRFLOW_CTX_TASK_ID='tarea_formateo' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T00:28:19.235584+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T00:28:19.235584+00:00'
[2025-03-20T19:28:24.648-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-20T19:28:29.031-0500] {logging_mixin.py:190} INFO - Hay 231 archivos en el folder data/rawdata/
[2025-03-20T19:28:47.091-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-20T19:28:47.095-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-20T19:28:47.095-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=proceso_etl, task_id=tarea_formateo, run_id=manual__2025-03-21T00:28:19.235584+00:00, execution_date=20250321T002819, start_date=20250321T002824, end_date=20250321T002847
[2025-03-20T19:28:47.176-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-20T19:28:47.189-0500] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-20T19:28:47.205-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
