[2025-03-20T16:44:31.630-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T16:44:31.639-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: proceso_etl_dinamico.tarea_datawrangling manual__2025-03-20T21:43:55.452145+00:00 [queued]>
[2025-03-20T16:44:31.644-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: proceso_etl_dinamico.tarea_datawrangling manual__2025-03-20T21:43:55.452145+00:00 [queued]>
[2025-03-20T16:44:31.644-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-20T16:44:31.661-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): tarea_datawrangling> on 2025-03-20 21:43:55.452145+00:00
[2025-03-20T16:44:31.668-0500] {standard_task_runner.py:72} INFO - Started process 214210 to run task
[2025-03-20T16:44:31.670-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'proceso_etl_dinamico', 'tarea_datawrangling', 'manual__2025-03-20T21:43:55.452145+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmp60l2o2mj']
[2025-03-20T16:44:31.671-0500] {standard_task_runner.py:105} INFO - Job 10: Subtask tarea_datawrangling
[2025-03-20T16:44:31.700-0500] {task_command.py:467} INFO - Running <TaskInstance: proceso_etl_dinamico.tarea_datawrangling manual__2025-03-20T21:43:55.452145+00:00 [running]> on host luis-GF65
[2025-03-20T16:44:31.754-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='proceso_etl_dinamico' AIRFLOW_CTX_TASK_ID='tarea_datawrangling' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T21:43:55.452145+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T21:43:55.452145+00:00'
[2025-03-20T16:44:31.754-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-20T16:44:59.572-0500] {data_wrangling.py:149} INFO - 1. Terminando formateo!!
[2025-03-20T16:45:10.118-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:45:15.116-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:45:15.124-0500] {data_wrangling.py:186} ERROR - Los clasificados como 'venta' no son considerablemente más caros que los de alquiler. Verificar información
[2025-03-20T16:45:15.124-0500] {data_wrangling.py:187} INFO - Los clasificados como 'venta' cuestan 1.0 veces más que los de alquiler
[2025-03-20T16:45:15.125-0500] {data_wrangling.py:199} INFO - 2. Terminando clasificación de propiedades con data inconsistente!!
[2025-03-20T16:45:52.266-0500] {logging_mixin.py:190} INFO - Error con las coordenadas {'id': 107, 'latitud': -12.139996599999998, 'longitud': -77.0236548}: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2025-03-20T16:46:01.344-0500] {data_wrangling.py:214} INFO - 3. Terminando obtención de dirección y precisión de coordenadas!!
[2025-03-20T16:46:16.567-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:46:16.568-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:46:18.541-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:46:18.916-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:46:32.432-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:46:35.410-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:46:39.909-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:46:40.729-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:46:49.070-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:46:49.078-0500] {logging_mixin.py:190} WARNING - /home/luis/Proyectos/PrecioDeDepartamentos/Precios-depas-git/ProyectoDepas/2.0.StaggingLayer/StagingLayerProject/Pipeline/utils/general.py:23 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-20T16:46:49.080-0500] {logging_mixin.py:190} INFO - El % de coincidencias para la columna 'area': 95.00% de 100
[2025-03-20T16:46:49.082-0500] {logging_mixin.py:190} WARNING - /home/luis/Proyectos/PrecioDeDepartamentos/Precios-depas-git/ProyectoDepas/2.0.StaggingLayer/StagingLayerProject/Pipeline/utils/general.py:23 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-20T16:46:49.083-0500] {logging_mixin.py:190} INFO - El % de coincidencias para la columna 'dormitorios': 97.95% de 146
[2025-03-20T16:46:49.085-0500] {logging_mixin.py:190} WARNING - /home/luis/Proyectos/PrecioDeDepartamentos/Precios-depas-git/ProyectoDepas/2.0.StaggingLayer/StagingLayerProject/Pipeline/utils/general.py:23 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-20T16:46:49.087-0500] {logging_mixin.py:190} INFO - El % de coincidencias para la columna 'banos': 87.88% de 132
[2025-03-20T16:46:49.089-0500] {logging_mixin.py:190} WARNING - /home/luis/Proyectos/PrecioDeDepartamentos/Precios-depas-git/ProyectoDepas/2.0.StaggingLayer/StagingLayerProject/Pipeline/utils/general.py:23 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-20T16:46:49.090-0500] {logging_mixin.py:190} INFO - El % de coincidencias para la columna 'antiguedad': 85.71% de 35
[2025-03-20T16:46:49.091-0500] {data_wrangling.py:264} INFO - La variable area redujo 6 nulos
[2025-03-20T16:46:49.091-0500] {data_wrangling.py:264} INFO - La variable dormitorios redujo 13 nulos
[2025-03-20T16:46:49.092-0500] {data_wrangling.py:264} INFO - La variable banos redujo 9 nulos
[2025-03-20T16:46:49.093-0500] {data_wrangling.py:264} INFO - La variable antiguedad redujo 0 nulos
[2025-03-20T16:46:49.094-0500] {data_wrangling.py:273} INFO - 4. Terminando imputación de nulos de variables básicas con la descripción!!
[2025-03-20T16:46:55.125-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T16:46:56.345-0500] {data_wrangling.py:325} INFO - 5. Terminando imputación de nulos de coordenadas con la descripción!!
[2025-03-20T16:46:58.972-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-20T16:46:58.975-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-20T16:46:58.975-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=proceso_etl_dinamico, task_id=tarea_datawrangling, run_id=manual__2025-03-20T21:43:55.452145+00:00, execution_date=20250320T214355, start_date=20250320T214431, end_date=20250320T214658
[2025-03-20T16:46:59.026-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-20T16:46:59.035-0500] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-20T16:46:59.047-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
