[2025-03-20T18:56:37.802-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T18:56:37.810-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: proceso_etl.tarea_formateo manual__2025-03-20T23:56:33.365950+00:00 [queued]>
[2025-03-20T18:56:37.814-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: proceso_etl.tarea_formateo manual__2025-03-20T23:56:33.365950+00:00 [queued]>
[2025-03-20T18:56:37.815-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-20T18:56:37.838-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): tarea_formateo> on 2025-03-20 23:56:33.365950+00:00
[2025-03-20T18:56:37.847-0500] {standard_task_runner.py:72} INFO - Started process 30746 to run task
[2025-03-20T18:56:37.849-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'proceso_etl', 'tarea_formateo', 'manual__2025-03-20T23:56:33.365950+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmps8r9w8k8']
[2025-03-20T18:56:37.850-0500] {standard_task_runner.py:105} INFO - Job 45: Subtask tarea_formateo
[2025-03-20T18:56:37.891-0500] {task_command.py:467} INFO - Running <TaskInstance: proceso_etl.tarea_formateo manual__2025-03-20T23:56:33.365950+00:00 [running]> on host luis-GF65
[2025-03-20T18:56:37.949-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='proceso_etl' AIRFLOW_CTX_TASK_ID='tarea_formateo' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T23:56:33.365950+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T23:56:33.365950+00:00'
[2025-03-20T18:56:37.950-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-20T18:56:40.379-0500] {logging_mixin.py:190} INFO - Hay 231 archivos en el folder data/rawdata/
[2025-03-20T18:56:55.953-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-20T18:56:55.955-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-20T18:56:55.956-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=proceso_etl, task_id=tarea_formateo, run_id=manual__2025-03-20T23:56:33.365950+00:00, execution_date=20250320T235633, start_date=20250320T235637, end_date=20250320T235655
[2025-03-20T18:56:56.038-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-20T18:56:56.050-0500] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-20T18:56:56.075-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
