[2025-03-20T17:56:21.652-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T17:56:21.661-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: proceso_etl.tarea_datawrangling manual__2025-03-20T22:52:26.436338+00:00 [queued]>
[2025-03-20T17:56:21.665-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: proceso_etl.tarea_datawrangling manual__2025-03-20T22:52:26.436338+00:00 [queued]>
[2025-03-20T17:56:21.665-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-20T17:56:21.683-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): tarea_datawrangling> on 2025-03-20 22:52:26.436338+00:00
[2025-03-20T17:56:21.690-0500] {standard_task_runner.py:72} INFO - Started process 251816 to run task
[2025-03-20T17:56:21.692-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'proceso_etl', 'tarea_datawrangling', 'manual__2025-03-20T22:52:26.436338+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpdh6cl877']
[2025-03-20T17:56:21.694-0500] {standard_task_runner.py:105} INFO - Job 27: Subtask tarea_datawrangling
[2025-03-20T17:56:21.721-0500] {task_command.py:467} INFO - Running <TaskInstance: proceso_etl.tarea_datawrangling manual__2025-03-20T22:52:26.436338+00:00 [running]> on host luis-GF65
[2025-03-20T17:56:21.777-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='proceso_etl' AIRFLOW_CTX_TASK_ID='tarea_datawrangling' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T22:52:26.436338+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T22:52:26.436338+00:00'
[2025-03-20T17:56:21.778-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-20T17:56:39.281-0500] {data_wrangling.py:149} INFO - 1. Terminando formateo!!
[2025-03-20T17:56:47.607-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T17:56:50.247-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T17:56:50.261-0500] {data_wrangling.py:186} ERROR - Los clasificados como 'venta' no son considerablemente más caros que los de alquiler. Verificar información
[2025-03-20T17:56:50.261-0500] {data_wrangling.py:187} INFO - Los clasificados como 'venta' cuestan 1.0 veces más que los de alquiler
[2025-03-20T17:56:50.263-0500] {data_wrangling.py:199} INFO - 2. Terminando clasificación de propiedades con data inconsistente!!
[2025-03-20T17:57:34.741-0500] {data_wrangling.py:214} INFO - 3. Terminando obtención de dirección y precisión de coordenadas!!
[2025-03-20T17:57:51.382-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T17:57:51.793-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T17:57:55.475-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T17:57:55.536-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T17:58:06.736-0500] {_base_client.py:1099} INFO - Retrying request to /chat/completions in 0.493695 seconds
[2025-03-20T17:58:08.303-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T17:58:08.341-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T17:58:11.243-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T17:58:17.180-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T17:58:18.209-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T17:58:18.218-0500] {logging_mixin.py:190} WARNING - /home/luis/Proyectos/PrecioDeDepartamentos/Precios-depas-git/ProyectoDepas/2.0.StaggingLayer/StagingLayerProject/Pipeline/utils/general.py:23 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-20T17:58:18.220-0500] {logging_mixin.py:190} INFO - El % de coincidencias para la columna 'area': 93.33% de 105
[2025-03-20T17:58:18.222-0500] {logging_mixin.py:190} WARNING - /home/luis/Proyectos/PrecioDeDepartamentos/Precios-depas-git/ProyectoDepas/2.0.StaggingLayer/StagingLayerProject/Pipeline/utils/general.py:23 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-20T17:58:18.223-0500] {logging_mixin.py:190} INFO - El % de coincidencias para la columna 'dormitorios': 97.14% de 140
[2025-03-20T17:58:18.225-0500] {logging_mixin.py:190} WARNING - /home/luis/Proyectos/PrecioDeDepartamentos/Precios-depas-git/ProyectoDepas/2.0.StaggingLayer/StagingLayerProject/Pipeline/utils/general.py:23 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-20T17:58:18.227-0500] {logging_mixin.py:190} INFO - El % de coincidencias para la columna 'banos': 84.33% de 134
[2025-03-20T17:58:18.229-0500] {logging_mixin.py:190} WARNING - /home/luis/Proyectos/PrecioDeDepartamentos/Precios-depas-git/ProyectoDepas/2.0.StaggingLayer/StagingLayerProject/Pipeline/utils/general.py:23 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-20T17:58:18.230-0500] {logging_mixin.py:190} INFO - El % de coincidencias para la columna 'antiguedad': 94.59% de 37
[2025-03-20T17:58:18.230-0500] {data_wrangling.py:264} INFO - La variable area redujo 5 nulos
[2025-03-20T17:58:18.231-0500] {data_wrangling.py:264} INFO - La variable dormitorios redujo 13 nulos
[2025-03-20T17:58:18.231-0500] {data_wrangling.py:264} INFO - La variable banos redujo 7 nulos
[2025-03-20T17:58:18.232-0500] {data_wrangling.py:264} INFO - La variable antiguedad redujo 0 nulos
[2025-03-20T17:58:18.233-0500] {data_wrangling.py:273} INFO - 4. Terminando imputación de nulos de variables básicas con la descripción!!
[2025-03-20T17:58:24.761-0500] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-03-20T17:58:26.400-0500] {data_wrangling.py:325} INFO - 5. Terminando imputación de nulos de coordenadas con la descripción!!
[2025-03-20T17:58:28.822-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-20T17:58:28.825-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-20T17:58:28.825-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=proceso_etl, task_id=tarea_datawrangling, run_id=manual__2025-03-20T22:52:26.436338+00:00, execution_date=20250320T225226, start_date=20250320T225621, end_date=20250320T225828
[2025-03-20T17:58:28.890-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-20T17:58:28.895-0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-20T17:58:28.895-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
