[2025-03-20T17:41:14.032-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T17:41:14.044-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: proceso_etl.tarea_limpieza manual__2025-03-20T22:38:04.811675+00:00 [queued]>
[2025-03-20T17:41:14.050-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: proceso_etl.tarea_limpieza manual__2025-03-20T22:38:04.811675+00:00 [queued]>
[2025-03-20T17:41:14.050-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-20T17:41:14.070-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): tarea_limpieza> on 2025-03-20 22:38:04.811675+00:00
[2025-03-20T17:41:14.076-0500] {standard_task_runner.py:72} INFO - Started process 243886 to run task
[2025-03-20T17:41:14.078-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'proceso_etl', 'tarea_limpieza', 'manual__2025-03-20T22:38:04.811675+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmp7ehy5pxz']
[2025-03-20T17:41:14.079-0500] {standard_task_runner.py:105} INFO - Job 15: Subtask tarea_limpieza
[2025-03-20T17:41:14.108-0500] {task_command.py:467} INFO - Running <TaskInstance: proceso_etl.tarea_limpieza manual__2025-03-20T22:38:04.811675+00:00 [running]> on host luis-GF65
[2025-03-20T17:41:14.163-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='proceso_etl' AIRFLOW_CTX_TASK_ID='tarea_limpieza' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T22:38:04.811675+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T22:38:04.811675+00:00'
[2025-03-20T17:41:14.164-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-20T17:41:16.922-0500] {limpieza.py:53} INFO - 1. Terminando pre-limpieza antes del análisis !!
[2025-03-20T17:41:16.966-0500] {limpieza.py:74} INFO - 2. Terminando corrección de coordenadas y distrito !!
[2025-03-20T17:41:16.971-0500] {limpieza.py:92} INFO - Relación en distrito barranco: 2.29
[2025-03-20T17:41:16.972-0500] {limpieza.py:96} INFO - Relación global entre preciosxm2: 2.29
[2025-03-20T17:41:16.973-0500] {limpieza.py:103} INFO - 3. Terminando corrección de precios extremadamente bajos !!
[2025-03-20T17:41:16.983-0500] {logging_mixin.py:190} WARNING - /home/luis/Proyectos/PrecioDeDepartamentos/Precios-depas-git/ProyectoDepas/2.0.StaggingLayer/StagingLayerProject/Pipeline/tasks/limpieza.py:116 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-20T17:41:16.992-0500] {limpieza.py:130} INFO - 4. Terminando tratamiento de duplicados !!
[2025-03-20T17:41:16.993-0500] {logging_mixin.py:190} INFO - No existen valores nulos en area
[2025-03-20T17:41:16.993-0500] {logging_mixin.py:190} INFO - No existen valores nulos en antiguedad
[2025-03-20T17:41:17.002-0500] {logging_mixin.py:190} WARNING - /home/luis/Proyectos/PrecioDeDepartamentos/Precios-depas-git/ProyectoDepas/2.0.StaggingLayer/StagingLayerProject/Pipeline/tasks/limpieza.py:195 FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
[2025-03-20T17:41:17.023-0500] {limpieza.py:212} INFO - 7. Terminando última limpieza antes de EDA !!
[2025-03-20T17:41:20.460-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-20T17:41:20.474-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-20T17:41:20.475-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=proceso_etl, task_id=tarea_limpieza, run_id=manual__2025-03-20T22:38:04.811675+00:00, execution_date=20250320T223804, start_date=20250320T224114, end_date=20250320T224120
[2025-03-20T17:41:20.574-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-20T17:41:20.584-0500] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-20T17:41:20.595-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
